version: '3.8'

services:
  app:
    image: token2049-app
    build:
      context: .
    volumes:
      - ./src/:/var/www
    ports:
      - 9000:9000
    depends_on:
      - db
      - redis
    networks:
      - token2049

  webserver:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - token2049

  queue-worker:
    image: token2049-app
    build:
      context: .
    volumes:
      - ./src/:/var/www
    depends_on:
      - db
      - app
      - redis
    working_dir: /var/www
    command: php artisan queue:work database --tries=3 --sleep=3
    restart: always
    networks:
      - token2049

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: token2049_db
      MYSQL_USER: db_access
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_vol:/var/lib/mysql
    networks:
      - token2049

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - token2049

  app-test:
    image: token2049-app
    volumes:
      - ./src/:/var/www
    working_dir: /var/www
    depends_on:
      - test-db
    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: test-db
      DB_PORT: 3306
      DB_DATABASE: token2049_test_db
      DB_USERNAME: db_access
      DB_PASSWORD: secret
    command: php artisan test
    networks:
      - token2049

  test-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: token2049_test_db
      MYSQL_USER: db_access
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    networks:
      - token2049

networks:
  token2049:
    driver: bridge
